### ISSUE TITLE
TestTransaction fails

### ISSUE THREAD

**Issue by l0rb** [chainside/btcpy#12]
On a fresh clone of the repository running
`python3 unit.py TestTransaction`
fails with the following Error:

`Traceback (most recent call last):
  File "unit.py", line 190, in test_txid
    self.assertEqual(Transaction.unhexlify(data['raw']).txid, data['txid'])
  File "/home/lorb/.local/lib/python3.5/site-packages/btcpy/structs/transaction.py", line 333, in unhexlify
    return cls.deserialize(bytearray(unhexlify(string)))
  File "/home/lorb/.local/lib/python3.5/site-packages/btcpy/structs/transaction.py", line 338, in deserialize
    result = parser.get_next_tx(cls is MutableTransaction)
  File "/home/lorb/.local/lib/python3.5/site-packages/btcpy/lib/parsing.py", line 232, in get_next_tx
    result = Transaction(version, txins, txouts, locktime)
  File "/home/lorb/.local/lib/python3.5/site-packages/btcpy/structs/transaction.py", line 360, in __init__
    if txid != self.txid and txid is not None:
  File "/home/lorb/.local/lib/python3.5/site-packages/btcpy/structs/transaction.py", line 378, in txid
    return self.hash()
  File "/home/lorb/.local/lib/python3.5/site-packages/btcpy/lib/types.py", line 26, in wrapper
    object.__setattr__(self, cache, method(self))
  File "/home/lorb/.local/lib/python3.5/site-packages/btcpy/structs/transaction.py", line 374, in hash
    return hexlify(stream.hash()[::-1]).decode()
AttributeError: 'Stream' object has no attribute 'hash'
`

This is with Python 3.5.3

**Comment by SimoneBronzini** [comment]
Thanks for your feedback. This is quite strange, as you can see [here](https://github.com/chainside/btcpy/commit/eac20d449d9d3f7e2fb72c96a1ea02f55d46aeee#diff-04cc62bd767ef0b7f0a857cb1f80cf47R374), the `hash` method was removed from `Stream` and replaced everywhere it was used. On the current version (tag 0.2.4) tests are running fine. How did you get your version of the codebase? Did you clone this repo or downloaded it from pypi?

**Comment by l0rb** [comment]
This is with the code from pypi

**Comment by SimoneBronzini** [comment]
New version on pypi coming

**Comment by SimoneBronzini** [comment]
New version released. Please let me know if there are other problems.
