### ISSUE TITLE
Error: StopIteration: Trying to shift empty string

### ISSUE THREAD

**Issue by zzir** [chainside/btcpy#22]
block 260066

```
Traceback (most recent call last):
  File "sync_service_num.py", line 176, in <module>
    deser.start(None, args.start, args.end)
  File "sync_service_num.py", line 56, in start
    block = BCDBlock.unhexlify(block_hex)
  File "/home/bcdw/zzzzzz/block_api/bcd_deserialize.py", line 22, in unhexlify
    return BCDBlock.deserialize(bytearray(binascii.unhexlify(string)))
  File "/home/bcdw/zzzzzz/block_api/bcd_deserialize.py", line 28, in deserialize
    txns = parser.get_txns()
  File "/home/bcdw/zzzzzz/block_api/bcd_deserialize.py", line 78, in get_txns
    txns.append(txns_parser.get_next_tx())
  File "/home/bcdw/zzzzzz/block_api/bcd_deserialize.py", line 235, in get_next_tx
    txouts = self._txouts()
  File "/usr/local/lib/python3.6/dist-packages/btcpy/lib/parsing.py", line 185, in _txouts
    return [self._txout(i) for i in range(self.parse_varint())]
  File "/usr/local/lib/python3.6/dist-packages/btcpy/lib/parsing.py", line 185, in <listcomp>
    return [self._txout(i) for i in range(self.parse_varint())]
  File "/home/bcdw/zzzzzz/block_api/bcd_deserialize.py", line 225, in _txout
    script = ScriptBuilder.identify(self >> self.parse_varint())
  File "/usr/local/lib/python3.6/dist-packages/btcpy/structs/script.py", line 1231, in identify
    candidate = script_type(Script(raw_script))
  File "/usr/local/lib/python3.6/dist-packages/btcpy/structs/script.py", line 800, in __init__
    object.__setattr__(self, 'data', self.verify(param.body))
  File "/usr/local/lib/python3.6/dist-packages/btcpy/structs/script.py", line 519, in verify
    args = [data for data in parser.match(cls.template)]
  File "/usr/local/lib/python3.6/dist-packages/btcpy/lib/parsing.py", line 257, in match
    pushes.append(self.require_push(op[1:-1]))
  File "/usr/local/lib/python3.6/dist-packages/btcpy/lib/parsing.py", line 291, in require_push
    push_data = self.get_push()
  File "/usr/local/lib/python3.6/dist-packages/btcpy/lib/parsing.py", line 315, in get_push
    curr_op = next(self)
  File "/usr/local/lib/python3.6/dist-packages/btcpy/lib/parsing.py", line 64, in __next__
    return (self >> 1)[0]
  File "/usr/local/lib/python3.6/dist-packages/btcpy/lib/parsing.py", line 49, in __rshift__
    raise StopIteration('Trying to shift empty string')
StopIteration: Trying to shift empty string
```

**Comment by SimoneBronzini** [comment]
Hi, thanks for the report! The version currently on this GitHub repo already has the issue fixed. It will be included in the next pypi version!
